### ISSUE TITLE
account.register gets wrong url_for server address

### ISSUE THREAD

**Issue by Mattpwinchester** [hack4impact/flask-base#112]
After deploying the code base to an EC2 instance I have an email generation problem where the confirm_link = url_for('account.confirm', token=token, _external=True) is creating a url of: 

127.0.0.1:8000/account/confirm-account/<token>

I tried setting the app.config['SERVER_NAME'] to the name of my server as seen here:

http://stackoverflow.com/questions/12162634/where-do-i-define-the-domain-to-be-used-by-url-for-in-flask

However, that didn't work. I did manage to get it to work though by turning off the _external=True flag and manually setting the name of the server as a variable. Just wondering if there was a better way to go about this (maybe defining the server name in Local?) or if I'm missing something to how this whole flask stack works.

**Comment by abhisuri97** [comment]
The `SERVER_NAME` variable is set based on your server settings from what I can understand. I am not sure exactly what this means for Amazon EC2. But open a PR with your solution and I'll take a look at it and see whats the best way to integrate it. Just as a general question, are you running your application with the `FLASK_CONFIG` env var set to `production`?

**Comment by Mattpwinchester** [comment]
I have the environment variable set to development. 

Isn't the SERVER_NAME supposed to be set in the env file? The server setup I'm running is a nginx server pointing upstream to this (flask-base) server instance which I run using the Foreman config:

redis: redis-server
web: python -u manage.py runserver --host 127.0.0.1 --port 8000
worker: python -u manage.py run_worker 

I tried it with the host defined like that and without it with the same results.

**Comment by abhisuri97** [comment]
just wondering. if you set the environment variable `FLASK_CONFIG=production` does that change anything? sorry for being late getting to this, had a few midterms this week.

**Comment by Mattpwinchester** [comment]
Sorry about taking so long to respond. 

I tried setting the FLASK_CONFIG=production flag in the .env file with the other flask parameters and it doesn't appear to be changing anything other than now the server gives me a RaygunProvider error: ApiKey not set, errors will not be transmitted. 

Shut down the server and restarted it with the same issue. The only method I have to work around this issue is to set the external flag in url_for() to false and then have a string for my server name that I append with the internal URL. This is sloppy and I would like to have flask-base give me the name of the website if possible. Even if I have to pre-load it into the env.py file or elsewhere.

**Comment by abhisuri97** [comment]
Hey Matt,
no problem on taking a while to respond. So I have tried to replicate this issue on my personal docker instance running on Digital ocean and it consistently puts my server domain in emails. If I manage to replicate the issue (or if someone else mentions it), I will merge the fix into the code base...but until then, a more maintainable fix would be to go to your `config.env` (or `.env` if you are using an older version of flask-base) file and add the line

`SERVER_NAME=http://yourdomainnamehere.blah`

Inside of `config.py` after line 58 add 
`SERVER_NAME = os.environ.get('SERVER_NAME') or 'http://localhost:5000'`

and make sure that you change `_external` mentions to `True` instead of `False`

**Comment by Mattpwinchester** [comment]
I followed your instructions and I am unable to view any of the website pages after restarting the server. 

My configuration is as follows: 

1) Using foreman to load the website,rq,redis:
redis: redis-server
web: python -u manage.py runserver  --port 8001
worker: python -u manage.py run_worker

2) Instance is run on an EC2 amazon instance (ubuntu 14.04)
3) Running in app.config development mode 
4) Nginx is handling SSL with letsencrypt and passing data upstream to the app running on port 8001. 

If you need clarification or additional information I will see what I can provide.

**Comment by abhisuri97** [comment]
sorry change the line to

`SERVER_NAME = os.environ.get('SERVER_NAME') or 'localhost:5000'`

OR for a slightly more managable configuration

on line 59:

`SERVER_NAME = 'localhost:5000'`

somewhere under `ProductionConfig` add

`SERVER_NAME = os.environ.get('SERVER_NAME')`

this fix will run on localhost 5000 in development mode and run on the actual server name when you set FLASK_CONFIG to production

i think that should work. I don't recall whether `SERVER_NAME` will need `http://` in front of it...most likely not now that i think about it.

**Comment by Mattpwinchester** [comment]
I tried your suggestions and it didn't work. Do I have to run the website on port 5000 in order for this to work? If so how do I change that to port 8001?

The website runs but I also get 404s for all of the webassets_external; How do I fix that?

**Comment by abhisuri97** [comment]
So on docker, you need to bind your local port (flask sets this to 5000) to whatever your external port will be.

**Comment by Mattpwinchester** [comment]
I'm not working with docker, the server is hosted on AWS. I have no idea how docker got added to this conversation. 

After trying your suggestions I still can't get the server to issue confirmation links with the server name I give it or even the port number.

**Comment by abhisuri97** [comment]
sorry about the docker thing, was working on a docker project while i wrote that. 

but since I haven't been able to replicate the issue on my end, the only thing i can think of is to have a separate environment variable just for your emailing URL (dont use `SERVER_NAME` since that is reserved by Flask for handling url routing etc) or just hardcoding it in as you said in your original message. I don't have a ton of experience launching things on AWS so I am not the best person to reach out to about this. 

Also about your question regarding whether it has to be on port 5000, you can change that by explicitly adding the runserver command in manager.py as shown here http://stackoverflow.com/questions/34824988/run-app-from-flask-migrate-manager
