### ISSUE TITLE
RQ task on startup

### ISSUE THREAD

**Issue by Mattpwinchester** [hack4impact/flask-base#119]
I'm testing to see how to get a RQ task to run on server startup similar to the email task. I assume that I'm supposed to have the task enqueued inside the context of the application. I tried running it inside the app/__init__.py python file but I got an exception:

raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context

Where should I put the code for running the task?

**Comment by abhisuri97** [comment]
Refer to here an example of enqueuing the task https://github.com/hack4impact/reading-terminal-market/blob/master/app/vendor/views.py#L563 

This gives an example of how to make the method. you can just put that method anywhere in the app. 
https://github.com/hack4impact/reading-terminal-market/blob/master/app/vendor/views.py#L585

**Comment by Mattpwinchester** [comment]
I am using that exact method for my task calls in some of my views; The problem is that when I try to run the same code in the manager.py app or the __init__.py code it causes an exception as mentioned above. 

Looking around I found the flask script tag: @app.before_first_request

and so I tried:

@app.before_first_request
def test_func():
    print "TEST FUNC: " + str(datetime.now())
    get_queue().enqueue(my_task)

Which works but the problem is that I believe that I need to visit a page on the server before the function starts. If there was a means to begin a task before that happens it would be preferable else, I'll continue down this path.

**Comment by sandlerben** [comment]
This should be possible. Can you share your code?

**Comment by Mattpwinchester** [comment]
@sandlerben I can but instead of making a repo and pushing all my code into it, is there a particular file and/or function you would like to look at?

**Comment by sandlerben** [comment]
Yeah, push a [gist](https://gist.github.com/) containing your modified `__init__.py` which didn't work.

**Comment by Mattpwinchester** [comment]
https://gist.github.com/Mattpwinchester/0bf556492f2b3a26484f6b0ccf19864c

Both files are in the same directory (app/)

**Comment by sandlerben** [comment]
Lines 8 and 9 of `time_check` should be unnecessary since your function doesn't use any state from `app`.

**Comment by sandlerben** [comment]
If it doesn't work even after removing those lines, can you paste your error here?

**Comment by Mattpwinchester** [comment]
I would prefer to have the create_app functionality in order to pull data from my application's configuration. That way I can use the config's settings for mail, database and Redis values set in my .env file. 

The error I was getting was that create_app couldn't find the app file inside of the test_task.py file. I assume this is because the app directory is bundled so the various blueprint apps can find it while a task in the same directory may have an issue detecting it through an import statement.

**Comment by Mattpwinchester** [comment]
I solved the issue by changing the code:

from app import create_app

[function definition]
app = create_app(os.getenv('FLASK_CONFIG') or 'default')
    with app.app_context():


to the simpler:

from flask import current_app as app

[function definition]

[get information from app.config]


This works in testing but is there something I should be concerned of? possibly regarding security or scope? I'm not quite sure what is the difference between the two sets of code.

**Comment by sandlerben** [comment]
I understand the confusion. The reason why that email function creates a new
app context is because when that function executes, it is running in the worker
process and doesn't have access to the state from the app process. In contrast,
your function doesn't require any state from the app process, so you do not need
to create a new app context.  





On Mon, Feb 27, 2017 6:16 PM, Matthew Winchester notifications@github.com 
wrote:
I solved the issue by changing the code:

from app import create_app

[function definition]
app = create_app(os.getenv('FLASK_CONFIG') or 'default')
with app.app_context():

to the simpler:

from flask import current_app as app

[function definition]

[get information from app.config]

This works in testing but is there something I should be concerned of? possibly
regarding security or scope? I'm not quite sure what is the difference between
the two sets of code.

**Comment by Mattpwinchester** [comment]
> I understand the confusion. The reason why that email function creates a new
app context is because when that function executes, it is running in the worker
process and doesn't have access to the state from the app process. In contrast,
your function doesn't require any state from the app process, so you do not need
to create a new app context.

By context do you mean access to memory such as variables?

When you talk of "state of the app process", what do you mean? What the application currently processing?

**Comment by abhisuri97** [comment]
jumping in here. but basically, when a new worker task is initiated it needs the context of the application to work properly (if the task involves using some parts of the application itself). in the specific case of the email code we have, it mainly needs the initialized flask-mail instance and access to our environment variables. Of course we could have just imported those parts only, but we wanted to give users the ability to do more complex processing with the rest of the app state rather than just being restricted to an email function (e.g. one might want to do some extra step of keeping track of when an email was sent in a db table etc).

**Comment by Mattpwinchester** [comment]
Cool, thanks.
