### ISSUE TITLE
Database CRUD/ dashboard?

### ISSUE THREAD

**Issue by kc1** [hack4impact/flask-base#163]
Hi guys,

Thanks for putting together this project. I've extended the Models, and I now need to be able to modify perform crud operations to the DB tables, kind of like in the django admin section. Before I try to roll my own solution , what approach would be most efficient to allow this? I have read through http://hack4impact.github.io/flask-base/manage_commands/ and I see this is partially discussed in make_shell_context. Is there a plugin that you would suggest? I'd be interested in getting your thoughts.

Thanks,

KC

**Comment by sandlerben** [comment]
Hey KC,

I don't think `make_shell_context` is what you need, since that would require you to perform crud operations in the Python shell. 

[flask-admin](https://flask-admin.readthedocs.io/en/latest/) seems to directly address your needs. Let me know what you think.

I could see how this admin interface might even be useful for us since we almost always add admin control for new models manually. If you agree, perhaps we could merge some of your changes upstream?

**Comment by kc1** [comment]
I've never contributed to an open source project before but I'd be happy to provide anything I come up with. perhaps you could improve on it and add it to the codebase. I've added flask admin locally and I will start work on this.

**Comment by sandlerben** [comment]
That sounds great 😄! You can just link us to the code in your app (if it's public)
