### ISSUE TITLE
Flask-admin integration.

### ISSUE THREAD

**Issue by IronFist16** [hack4impact/flask-base#171]
Hi,

Is there any plan for integrating both Flask-security and Flask-admin into flask-base?

Thank you

**Comment by kc1** [comment]
Funny you should ask that I'm interested in integrating flask-admin myself: https://github.com/hack4impact/flask-base/issues/168

**Comment by sandlerben** [comment]
Hey @IronFist16,

There are no plans right now, but as @kc1 mentioned there is some talk about flask-admin. I don't see much utility in integrating flask-security (given we are already using [flask-login](https://flask-login.readthedocs.io/en/latest/)), what do you think?

**Comment by IronFist16** [comment]
Well, I thought by doing so, will make this platform greater and more powerful, but I see that both flask-security and flask-base share a lot of common extensions though flask-security supports more data persistence than flask-base does. I haven't gone through all the differences, but like you said integrating flask-security might not be much of utility.

Integrating Flask-admin extension would be interesting for this platform.

**Comment by IronFist16** [comment]
@kc1 

Yea, I'm following your issue as well, I'm interested in doing so in my flask-based app.

**Comment by kc1** [comment]
@sandlerben 

Regarding https://github.com/hack4impact/flask-base/issues/168. @kyle-rosenbluth has taken a look at it and come up with a solution , but I'm unable to duplicate it in either windows or deployed to heroku. I'm not sure what to do next.

**Comment by sandlerben** [comment]
I'm not totally sure. I'm pretty busy right now because I'm graduating college this week but I can probably take a closer look next week.

**Comment by jstacoder** [comment]
Testing more, I’ve found it has a lot to do with the admin/index.html template, because both repos have that file, the error that gets thrown will depend on which blueprint was loaded first, and which version of admin/index.html is being loaded, I think a good solution would be to just namespace the admin templates here, flask-base/Admin/* or something, it would solve this whole issue because the jinja template loader wouldn’t be confused about which admin view wants which `admin/index.html`, because by default the loader doesn’t take the view into account when loading the templates, so when two blueprints share a template path, the first blueprint that was registered wins and its template is served, it’s possible to bake a template loader that does take the current view into account,  and doing that I was able to get flask-admin admin/index.html to load for flask admin and the flask base admin/index.html to load for flask base, but that’s wayyy to much for such a minor issue, not a good solution.

**Comment by jstacoder** [comment]
Although since it’s really a problem with the loader not loading the template from the blueprint requesting it, maybe it should be an issue for Jinja?

**Comment by jstacoder** [comment]
N/m just looked over the flask source, and they bake their own custom template loader that trys to load for the app and the blueprints, and it has a config setting EXPLAIN_TEMPLATE_LOADING that looks like it may clear a few things up, going to try now.

**Comment by kc1** [comment]
I have a solution if you look at https://github.com/kc1/flask-base. This was provided by https://stackoverflow.com/questions/50070979/wrong-dashboard-while-adding-flask-admin-to-project

**Comment by jstacoder** [comment]
of course changing all the templates works, thats what i meant when i suggested namespacing them, which i think would have been a little easier, and had the same effect. I thought the goal was to have them work together without changing the whole structure of the templates?  if it was to just have it work, then of course this suffices.

**Comment by abhisuri97** [comment]
At the moment, I don't think we're planning on including either flask-security or flask-admin. Closing this issue.
